%YAML:1.0
---
PNTRS: !!opencv-matrix
   rows: 4
   cols: 1
   dt: "3d"
   data: [ 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0. ]
CNRS: !!opencv-matrix
   rows: 4
   cols: 1
   dt: "2d"
   data: [ 0., 0., 0., 0., 0., 0., 0., 0. ]
